# Generated by Django 4.2.4 on 2023-08-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_color_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
